apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
  labels:
    app: webapp
spec:
  type: NodePort  
  selector:
    app: webapp
  ports:
    - name: http
      port: 80        
      targetPort: 80  
      nodePort: 30080 
